name: Python style
on: [pull_request]
jobs:

  qa:
    name: Quality check
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: 3.8
      - name: Run unit tests
        # https://github.com/wemake-services/wemake-python-styleguide/issues/519
        run: |
          pip install flake8-bandit==1.0.2
          python setup.py test
        env:
          NUMBA_DISABLE_JIT: 1
      - name: Wemake Python Stylguide
        uses: wemake-services/wemake-python-styleguide@0.15.2
        continue-on-error: true
        with:
          reporter: 'github-pr-review'
        env:
          NUMBA_DISABLE_JIT: 1
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
